name: Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-ecosystem/action-size@v2
        id: size

      - uses: ./
        with:
          labels: ${{ steps.size.outputs.stale_labels }}

      - uses: step-security/action-add-labels@release
        with:
          labels: ${{ steps.size.outputs.new_label }}
